# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/depcore/pdftoolkit/models/template/columns.yaml

# Model Class name
modelClass: Depcore\PDFToolkit\Models\Template

# List Title
title: Manage Generators

# Link URL for each record
recordUrl: depcore/pdftoolkit/generator/create/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Display page numbers with pagination, disable to improve performance
showPageNumbers: true

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
    column: id
    direction: asc

# Toolbar widget configuration
toolbar:
    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
